#REFERENCE
#https://github.com/noamross/jekyll-site/blob/master/_config.yml


# name: Vijadh

baseurl: "/"

destination: ./docs

environment: development

production_url : http://vijadh.com/

plugins_dir: ./_plugins

version: "?v=1.2"

#plugins:
#  - directory_tag


plugins:
  - jekyll-redirect-from
#https://github.com/jekyll/jekyll-redirect-from    
#https://superdevresources.com/redirects-jekyll-github-pages/