#REFERENCE
#https://github.com/noamross/jekyll-site/blob/master/_config.yml


# name: Vijadh

baseurl: "/"

destination: ./docs

environment: development

production_url : http://vijadh.com/

plugins_dir: ./_plugins 

version: "?v=1.0"

#plugins:
#  - directory_tag
