#REFERENCE
# https://github.com/noamross/jekyll-site/blob/master/_config.yml
#https://jekyllrb.com/docs/usage/#override-default-development-settings

#DEPLOY
#LOCAL
# jekyll serve
# jekyll build --watch
#PRODUCTION
# jekyll build

# name: Vijadh

baseurl: "/"

destination: ./docs

environment: development

production_url : http://vijadh.com/

plugins_dir: ./_plugins

version: "?v=1.3"

#plugins:
#  - directory_tag


plugins:
###########################################################
#BEGIN: REDIRECT  
  - jekyll-redirect-from
#REFERENCE  
# https://github.com/jekyll/jekyll-redirect-from    
# https://superdevresources.com/redirects-jekyll-github-pages/
#SYNTAX
# ---
# layout: redirected
# sitemap: false
# permalink: /
# redirect_to:  /wedding/
# ---
#END: REDIRECT  
###########################################################
